# Generated by Django 2.2.7 on 2019-11-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('problem_generator', models.CharField(choices=[('guillotine', 'guillotine'), ('florian', 'florian')], max_length=100)),
            ],
            options={
                'db_table': 'affinity',
                'unique_together': {('created_on', 'problem_generator', 'rows', 'cols')},
            },
        ),
    ]
