# Generated by Django 2.2.7 on 2019-12-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binpack', '0005_result_solution_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(blank=True, help_text='Tiles left', null=True),
        ),
    ]
