# Generated by Django 2.2.7 on 2020-01-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binpack', '0010_result_their_tiles_placed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AddField(
            model_name='result',
            name='problem_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
