# Generated by Django 2.2.7 on 2020-01-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binpack', '0012_result_improved_sel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='improved_sel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('problem_generator', 'rows', 'cols', 'problem_id', 'their_id', 'improved_sel')},
        ),
    ]
