# Generated by Django 2.2.7 on 2020-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binpack', '0013_auto_20200121_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='b_their_id',
            field=models.BigIntegerField(blank=True, help_text='ID from external dataset.', null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b_their_tiles_placed',
            field=models.BigIntegerField(blank=True, help_text='Amount of tiles placed with heuristics algorithm', null=True),
        ),
    ]
