# Generated by Django 2.2.7 on 2020-01-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binpack', '0014_auto_20200123_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='their_id',
            field=models.BigIntegerField(blank=True, help_text='ID from external dataset.', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='their_tiles_placed',
            field=models.BigIntegerField(blank=True, help_text='Amount of tiles placed with heuristics algorithm', null=True),
        ),
    ]
